### PR TITLE
draft for new event

### PR DESCRIPTION
**Pull request by lunardog**
February 15th.

@ashleysmart

### CODE REVIEW

**Comment by lunardog** [comment]
@ashleysmart so you have a working title for the 15th?

**Comment by takahi-i** [comment]
LGTM with Nits. Two headers in succession (japanese and english) in 29th line. English header is in 11-th line.

**Comment by lunardog** [comment]
@yoheikikuta I changed as suggested

@takahi-i I kept the double headers, removed the repeating schedule instead.

**Comment by lunardog** [comment]
You're welcome to split your talk and continue next time. 👍

**Comment by ashleysmart** [comment]
Haha..slight  problem with that idea is that is that the inverse reward policy talk on Saturday has captured my interest.. I'm very likely to see what I can code up for that next time

**Comment by ashleysmart** [comment]
Correction that was supposed to be "inverse reward design"

**Pull request merged**
