### PR TITLE
Put in working titles for talks

### PR DESCRIPTION
**Pull request by lunardog**
This is for January 17th 2019. 

We could use one or two more talks.

### CODE REVIEW

**Comment by lunardog** [comment]
@saurabhbhadada Would you like to talk this time? Your recent project on recipe titles can probably make a good talk.

**Comment by chie8842** [comment]
@lunardog If it's suirtable, I'll take it.:smile:
But Can we have it? I think we have many talks at next event.

**Comment by lunardog** [comment]
>  I think we have many talks at next event.
I only got two titles (Lain's and Dat's). Did I miss something? Please review and add.

**Comment by chie8842** [comment]
Chiba-san from Mercari also give a talk.
But I haven't get his title.

**Comment by lunardog** [comment]
Understood. Let's add Chiba-san's title when it comes and merge then.

**Comment by chie8842** [comment]
Thanks!
I asked him 2 days ago, but I'd like to wait for him and ask again next week.

**Comment by lunardog** [comment]
I'm merging this today. Missing information to be updated in a new pull request.

**Pull request merged**
